config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   resources :corsairs
  root 'static_pages#home'

 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: 'hey oh'
  end 

end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController

#créé un nouveau formulaire pour faire un nouveau profile. (comme le User = User.new ;) )
def new
	@corsair = Corsair.new

end 

#affiche le profile une fois remplit, grâce à l'id passé en paramètre.
def show
	@corsair = Corsair.find(params[:id])
end

#permet d'editer le profil, tujours en selectionnant le profil dans le hash en fonction de son ID.
def edit
	 @corsair = Corsair.find(params[:id])
end

#genere un nouveau profil en fonction de la methode corsaire_param définie en private.

def create
		@corsair = Corsair.new(corsair_params)
		if @corsair.save
		redirect_to @corsair
		else render 'new'
		end
	end

	#permet de réecrire le profil choisi

  def update
  	@corsair = Corsair.find(params[:id])
		if @corsair.update(corsair_params)
			redirect_to corsairs_path
		else 
			render 'edit'
		end
	end

	# delete le profil grâce à .destroy et redirige sur le corsair_path.

	def destroy
		@corsair = Corsair.find(params[:id])
		@corsair.destroy
		redirect_to corsairs_path
	end
		#liste les profils completés grâce au .all 
def index
	@corsairs = Corsair.all
end

private
	def corsair_params
  	params.require(:corsair).permit(:first_name, :age, :likeness)
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/_form.html.erb
</br>
</br>

<%= form_with model: @corsair, local: true do |form| %>

 <p align="center">
   <%= form.label "Quel est ton prénom ?" %><br>
   <%= form.text_field :first_name %>
 </p>
</br>
 <p align="center">
   <%= form.label "Quel âge as-tu mon enfant ?" %><br>
   <%= form.number_field :age %>
 </p>
 </br>
 </br>
 

 <p align="center"> Dans l'optique d'une étude de l'INSEE, nous avons besoin de savoir si tu es plutôt Hummus ou kebab ? (En vrai on s'en fou, j'compte pas te payer à manger)  </p>
 <div align="center">
	<%= form.radio_button :likeness, 'Kebab' %> Un bon gros grec ! 
	<%= form.radio_button :likeness, 'Hummus' %> Le hummus des familles.
</div>

 <p align="center">
   <%= form.submit "Valider" %>
 </p>

<% end %>

app/views/corsairs/edit.html.erb
</br>
</br>
</br>

<p> modifier : </p>
<%= render 'corsairs/form' %>

app/views/corsairs/index.html.erb
</br>
</br>

<!-- Index des Moussaillons -->
<h1 align="center">Liste des Moussaillons</h1>
<table align="center">
  <tr>

    <!-- Initiation d'un tableau -->

    <th>Prénom  </th>
    </br>
    <th>- Age</th>
  </tr>
 
  <% @corsairs.each do |corsair| %> 
    <tr align="center">
      <td><%= corsair.first_name %></td></br>


      <td><%= corsair.age %></td></br>
<!--CRUD -->

      <td><%= link_to "Afficher profil", corsair_path(corsair) %> - </td> 

      <td><%= link_to "Editer", edit_corsair_path(corsair) %> - </td></br>



      <td> - <%= link_to "Delete and exit", corsair_path(corsair),
              method: :delete,
              data: { confirm: 'Gros t\'es sérieux? ? t\'aimerais qu on te supprime comme ça en un click?' } %> </td></br>

    </tr>
  <% end %>
</table>

<p align = "center"> <%= link_to('Créer un nouveau profil', new_corsair_path ) %> </p> 

app/views/corsairs/new.html.erb
</br>
</br>
</br>
</br>

<h1 align="center"> Salut Moussaillon ! <h1>

	<%= render 'corsairs/form' %>

app/views/corsairs/show.html.erb
</br>
</br>
</br>
</br>


<div class="profil" align="center">
<h2> <%= @corsair.first_name %> </h2>
<p> Je suis d'accord avec toi, un bon gros <%= @corsair.likeness %> ça défonce tout !
<p> Et tu sais de quoi tu parles avec tes <%= @corsair.age %> ans d'expérience !</p>
<p>  <%= link_to('Editer', edit_corsair_path) %> </p> 
<p>  <%= link_to('Retour accueil', corsairs_path) %> </p> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",  root_path %></li>
        <li><%= link_to "Index des moussaillons",  corsairs_path %></li>
        <li><%= link_to "Nouveau moussaillon", new_corsair_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <title>ThpMoussaillons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <%= render 'layouts/header'%>


  <body>



  	
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron" align="center">
  <h1 align="center">Salut Moussaillon!</h1>
  <h3 align="center">
    Voici un petite liste de tous les moussailons de l'univers!
  </h3>
  <%=  link_to "Par ici Jeune padawan", 'corsairs', class: "btn btn-lg btn-primary" %>
</div>